const moviesList = [{


        "movie_id": 1,
        "title": "Harry Potter and the Sorcerers Stone",
        "category_name": "Fantasy",
        "thumb": "https://lh3.googleusercontent.com/42ZwafOz6sg9l7gXXh_5_d4VAvx7qObVOLtVHBTBTcUbhK0ffUJUtvvdf4hC2ZLb48s",
        "release_year": 2001,
        "running_time": 152,
        "rating_name": "PG",
        "disc_format_name": "DVD",
        "number_discs": 2,
        "viewing_format_name": "Widescreen",
        "aspect_ratio_name": "1.85:1",
        "status": 1,
        "time_stamp": "2015-09-25"
    },
    {
        "movie_id": 2,
        "title": "Harry Potter and the Chamber of Secrets",
        "category_name": "Fantasy",
        "thumb": "https://kbimages1-a.akamaihd.net/645388ae-94f7-41fe-8416-f3929f43414f/1200/1200/False/harry-potter-and-the-chamber-of-secrets-5.jpg",
        "release_year": 2002,
        "running_time": 161,
        "rating_name": "PG",
        "disc_format_name": "DVD",
        "number_discs": 2,
        "viewing_format_name": "Widescreen",
        "aspect_ratio_name": "1.85:1",
        "status": 1,
        "time_stamp": "2015-09-25"
    },
    {
        "movie_id": 3,
        "title": "Harry Potter and the Prison of Azkaban",
        "category_name": "Fantasy",
        "thumb": "https://vignette.wikia.nocookie.net/harrypotter/images/c/c4/7VTALkqjG40vby3uVIsp03d7yXy.jpg/revision/latest?cb=20130803163319",
        "release_year": 2004,
        "running_time": 142,
        "rating_name": "PG",
        "disc_format_name": "DVD",
        "number_discs": 2,
        "viewing_format_name": "Widescreen",
        "aspect_ratio_name": "1.85:1",
        "status": 1,
        "time_stamp": "2015-09-25"
    },
    {
        "movie_id": 4,
        "title": "Harry Potter and the Goblet of Fire",
        "category_name": "Fantasy",

        "thumb": "https://vignette.wikia.nocookie.net/harrypotter/images/2/2c/Goblet_of_Fire_Film_Poster.jpg/revision/latest?cb=20140817011104",
        "release_year": 2005,
        "running_time": 157,
        "rating_name": "PG-13",
        "disc_format_name": "DVD",
        "number_discs": 2,
        "viewing_format_name": "Widescreen",
        "aspect_ratio_name": "1.85:1",
        "status": 1,
        "time_stamp": "2015-09-25"
    },
    {
        "movie_id": 5,
        "title": "Harry Potter and the Order of the Phoenix",
        "category_name": "Fantasy",
        "thumb": "https://vignette.wikia.nocookie.net/harrypotter/images/7/70/Harry_Potter_and_the_Order_of_the_Phoenix.jpg/revision/latest?cb=20161002074140",
        "release_year": 2007,
        "running_time": 139,
        "rating_name": "PG-13",
        "disc_format_name": "DVD",
        "number_discs": 1,
        "viewing_format_name": "Widescreen",
        "aspect_ratio_name": "1.85:1",
        "status": 1,
        "time_stamp": "2015-09-25"
    },
    {
        "movie_id": 6,
        "title": "Harry Potter and the Half-Blood Prince",
        "category_name": "Fantasy",
        "thumb": "https://m.media-amazon.com/images/M/MV5BNzU3NDg4NTAyNV5BMl5BanBnXkFtZTcwOTg2ODg1Mg@@._V1_.jpg",
        "release_year": 2009,
        "running_time": 153,
        "rating_name": "PG",
        "disc_format_name": "DVD",
        "number_discs": 1,
        "viewing_format_name": "Widescreen",
        "aspect_ratio_name": "2.78:1",
        "status": 1,
        "time_stamp": "2015-09-25"
    },
    {
        "movie_id": 7,
        "title": "Harry Potter and the Deathly Hallows : Part I",
        "category_name": "Fantasy",
        "thumb": "https://m.media-amazon.com/images/M/MV5BMjIyZGU4YzUtNDkzYi00ZDRhLTljYzctYTMxMDQ4M2E0Y2YxXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_.jpg",
        "release_year": 2010,
        "running_time": 146,
        "rating_name": "PG-13",
        "disc_format_name": "Blu-ray + DVD",
        "number_discs": 1,
        "viewing_format_name": "Widescreen",
        "aspect_ratio_name": "1.85:1",
        "status": 1,
        "time_stamp": "2015-09-25"
    },
    {
        "movie_id": 8,
        "title": "Harry Potter and the Deathly Hallows : Part II",
        "category_name": "Fantasy",
        "thumb": "https://m.media-amazon.com/images/M/MV5BMjIyZGU4YzUtNDkzYi00ZDRhLTljYzctYTMxMDQ4M2E0Y2YxXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_.jpg",
        "release_year": 2011,
        "running_time": 130,
        "rating_name": "PG-13",
        "disc_format_name": "Blu-ray + DVD",
        "number_discs": 2,
        "viewing_format_name": "Widescreen",
        "aspect_ratio_name": "2.78:1",
        "status": 1,
        "time_stamp": "2015-09-25"
    },

]

export default moviesList